AllCops:
  Include:
  - "**/*.rake"
  - "**/Gemfile"
  - "**/Rakefile"
  Exclude:
  - "vendor/**/*"
  - "db/**/*"
  - "test/helpers/shared_database_connection.rb"
  DisplayCopNames: true
  TargetRubyVersion: 2.3
Rails:
  Enabled: true

Style/MethodDefParentheses:
  Description: Checks if the method definitions have or don't have parentheses.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#method-parens
  Enabled: true
  EnforcedStyle: require_no_parentheses
  SupportedStyles:
  - require_parentheses
  - require_no_parentheses

Metrics/LineLength:
  Description: Limit lines to 110 characters.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#80-character-limits
  Enabled: true
  Max: 110
  AllowURI: true
  URISchemes:
  - http
  - https

Style/ClassAndModuleChildren:
  Description: Checks style of children classes and modules.
  Enabled: false

Style/FrozenStringLiteralComment:
  Description: "Don't require frozne string literal comments"
  Enabled: false

Style/Documentation:
  Description: "Don't require documentation"
  Enabled: false

Lint/AssignmentInCondition:
  Description: 'Use assignments in conditions if you want.'
  Enabled: false
